FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose frontend port (React: 3000, Angular/Vue: 4200)
EXPOSE 3000

# Start frontend server
CMD ["npm", "run",  "dev"]
