
# Use Node.js 18 Alpine for a small and efficient image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install 

# Copy the entire project
COPY . .

# Expose the application port
EXPOSE 4000

# Start the application
CMD ["npm","run", "dev"]